# Generated by Django 2.2.28 on 2023-04-11 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_auditlog_bookings_content_events_notification_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='userID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_userID', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('type', models.IntegerField()),
                ('bookingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_bookingID', to='home.Bookings')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('status', models.IntegerField()),
                ('typeID', models.IntegerField()),
                ('bookingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_bookingID', to='home.Bookings')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.IntegerField()),
                ('typeID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paymentmethod_typeID', to='home.Payments')),
            ],
        ),
    ]
