# Generated by Django 2.2.28 on 2023-04-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20230411_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='name',
        ),
        migrations.AddField(
            model_name='roles',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roles',
            name='slug',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roles',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roles',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='roles',
            name='groupID',
            field=models.IntegerField(blank=True),
        ),
    ]
